### PR TITLE
Pdaf ipda refactor

### LINKED ISSUE #31: [TASK] Expose measurement likelihoods from PDAF for IPDA integration
### Description of task

Currently, the `IPDA` filter recomputes measurement likelihoods (`z_pred.pdf(z_k)`) inside `existence_prob_update()`.
However, these same likelihoods are already calculated internally in the `PDAF` during association weighting (`get_weights()`).

This causes duplicated computation and makes it harder to integrate IPDA and PDAF efficiently.

---

### **Proposed change**

Extend the `PDAF::Output` struct and `PDAF::step()` to include a vector of measurement likelihoods for the gated measurements.

Example:

```cpp
struct Output {
    Gauss_x x_;
    Gauss_x x_prediction;
    Gauss_z z_prediction;
    Gauss_xX x_updates;
    Arr_1Xb gated_measurements;
    Eigen::ArrayXd measurement_likelihoods;  // new field
};
```

In `step()`, compute and populate:

```cpp
Eigen::ArrayXd z_likelihoods(inside_meas.cols());
for (int i = 0; i < inside_meas.cols(); ++i)
    z_likelihoods(i) = z_pred.pdf(inside_meas.col(i));
```

and include it in the returned output.

---

### **Benefits**

* Eliminates redundant likelihood computation inside `IPDA`.
* Keeps likelihood generation within the PDAF, where it naturally belongs.
* Simplifies the IPDA implementation (can use the `existence_prob_update(likelihoods, ...)` overload).
* Improves performance and clarity.

---

### **Example integration**

After this change, `IPDA::step()` could do:

```cpp
auto [x_post, x_pred, z_pred, x_upd, gated_measurements, z_likelihoods] =
    PDAF::step(...);

double existence_probability_upd =
    IPDA::existence_prob_update(z_likelihoods, existence_prob_pred, config);
```

---

### Suggested Workflow

_No response_

### Specifications

_No response_

### Contacts

_No response_

### Code Quality

- [ ] Every function in header files are documented (inputs/returns/exceptions)
- [ ] The project has automated tests that cover MOST of the functions and branches in functions (pytest/gtest)
- [ ] The code is documented on the wiki (provide link)

### PR DESCRIPTION
**Pull request by jorgenfj**
Split the steps function of PDAF and IPDA into separate predict and update functions. 
Added z_likelihood function.
Removed redundant z_likelihood calculation in IPDA.

Fixed this if-statement bug that negated the function of the config arg.
```cpp
        if (!(z_measurements.cols() == 0 &&
              config.ipda.update_existence_probability_on_no_detection)) {
            existence_probability_upd = existence_prob_update(
                z_meas_inside, z_pred, existence_prob_pred, config);
        }
```

### CODE REVIEW

File: vortex-filtering/include/vortex_filtering/filters/ipda.hpp [hunk 1]
```diff
@@ -42,52 +46,139 @@ class IPDA {
...
+     * @return `std::tuple<Gauss_x, Gauss_z, double>` The predicted state,
+     * predicted measurement, and predicted existence probability
+     */
+    static std::tuple<Gauss_x, Gauss_z, double> predict(
+        const DynModT dyn_mod,
+        const SensModT& sens_mod,
+        double dt,
+        const State& state_est_prev,
+        const Arr_zXd& z_measurements,
+        Config& config) {
```
Comment (Andeshog) [inline vortex-filtering/include/vortex_filtering/filters/ipda.hpp]: Pass `dyn_mod` as reference here perhaps?

Also, using strong typing would make it much easier to use such a function IMO. Something like this maybe (also put the models together to decrease the number of inputs)
```C++
static PredictedState predict(const Models& models, const double dt, const State& prev_est_state, const Arr_zXd& z_measurements, Config& config)
```

Another thing, does it make sense to move the config update to a function call after this function is called, since it takes inputs and outputs to/from `predict` anyway. Reason; I would not expect a function named `predict` to also update one of the inputs

Comment (Andeshog) [reply vortex-filtering/include/vortex_filtering/filters/ipda.hpp]: The same applies to `update` below

File: vortex-filtering/include/vortex_filtering/filters/ipda.hpp [hunk 2]
```diff
@@ -42,52 +46,139 @@ class IPDA {
...
+     * @brief Calculates the predicted existence probability
+     * @param existence_prob_est (r_{k-1}) The previous existence probability.
+     * @param prob_of_survival (P_s) The probability of survival.
+     * @return The predicted existence probability (r_{k|k-1}).
+     */
+    static double existence_prediction(double existence_prob_est,
+                                       double prob_of_survival) {
+        double r_km1 = existence_prob_est;
+        double P_s = prob_of_survival;
+        return P_s * r_km1;  // (7.28)
```
Comment (Andeshog) [inline vortex-filtering/include/vortex_filtering/filters/ipda.hpp:262]: guess it would be nice to state the source as well, not just the equation number 😅

File: vortex-filtering/include/vortex_filtering/filters/ipda.hpp [hunk 3]
```diff
@@ -114,20 +205,19 @@ class IPDA {
...
      */
-    static double estimate_clutter_intensity(
-        const T::Gauss_z& z_pred,
-        double predicted_existence_probability,
-        double num_measurements,
-        Config config) {
+    static double estimate_clutter_intensity(const Gauss_z& z_pred,
+                                             double existence_prob_pred,
+                                             double num_measurements,
+                                             Config config) {
```
Comment (Andeshog) [inline vortex-filtering/include/vortex_filtering/filters/ipda.hpp]: Make `config` const ref perhaps

**Review by Andeshog — APPROVED** [review]
The comments apply up to several places btw, didnt want to repeat too much. And other than that LGTM (Approval with suggestions)
